<?xml version="1.0" encoding="utf-8"?><Database Name="DataSource" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=CountryComments.mssql.somee.com;Persist Security Info=True;User ID=nandofig_SQLLogin_1" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DataSourceConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.comments" Member="comments">
    <Type Name="comment">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="alphacode" Type="System.String" DbType="VarChar(3)" CanBeNull="true" />
      <Column Name="comments" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="data" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </Type>
  </Table>
</Database>